apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - authelia
  - aws-load-balancer-controller
  # - calico
  - cert-manager
  # - flagger
  # - kube-prometheus-stack
  - kyverno
  # - metrics-server
  - sealed-secrets
  - traefik
  - weave-gitops