---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  dependsOn:
    - name: ../../addons/cert-manager
  acme:
    email: ${acmeEmail}
    server: ${acmeServer}
    privateKeySecretRef:
      name: letsencrypt-nginx
    solvers:
      - http01:
          ingress:
            class: nginx