apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: mariadb
spec:
  releaseName: mariadb
  chart:
    spec:
      chart: mariadb
      version: ">=12.4.0,<13.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
  interval: 50m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    