apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: web
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: '23.1.0'
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  values:
    
    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1

    ingressRoute:
      dashboard:
        enabled: true

    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:927123100668:certificate/866eee85-fb0d-40d5-bd4c-db87f33390f0
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443
        service.beta.kubernetes.io/aws-load-balancer-type: alb