apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: patch-migrate-all-secrets-to-sealed-secrets.yaml
    target:
      kind: HelmRelease
  - path: patch-assign-to-node-by-label.yaml
    target:
      kind: HelmRelease