apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: patch-traefik-release.yaml
    target:
      kind: HelmRelease
      name: traefik
  - path: patch-mariadb-release.yaml
    target:
      kind: HelmRelease
      name: mariadb
