apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/sources
  - ../base/addons/aws-load-balancer-controller
  - ../base/addons/cert-manager
  - ../base/addons/mariadb
  - ../base/addons/redis
  - ../base/addons/sealed-secrets
  - ../base/addons/traefik
  - ../base/addons/weave-gitops
patches:
  - path: patch-node-selector-web.yaml
    target:
      kind: HelmRelease
      labelSelector: ng=web
  - path: patch-node-selector-apps.yaml
    target:
      kind: HelmRelease
      labelSelector: ng=apps 
  - path: patch-node-selector-data.yaml
    target:
      kind: HelmRelease
      labelSelector: ng=data