apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: patch-node-selector-web.yaml
    target:
      kind: HelmRelease
      labelSelector: ng=web
  - path: patch-node-selector-apps.yaml
    target:
      kind: HelmRelease
      labelSelector: ng=apps 
  - path: patch-node-selector-data.yaml
    target:
      kind: HelmRelease
      labelSelector: ng=data