apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/sources
  - ../base/addons/aws-load-balancer-controller
  - ../base/addons/cert-manager
  # - ../base/addons/mariadb
  # - ../base/addons/redis
  - ../base/addons/sealed-secrets
  - ../base/addons/traefik
  - ../base/addons/weave-gitops
patches:
  - path: patch-aws-load-balancer-controller.yaml
    target:
      kind: HelmRelease
      name: aws-load-balancer-controller
  - path: patch-cert-manager.yaml
    target:
      kind: HelmRelease
      name: cert-manager
  # - path: patch-mariadb.yaml
  #   target:
  #     kind: HelmRelease
  #     name: mariadb
  # - path: patch-redis.yaml
  #   target:
  #     kind: HelmRelease
  #     name: redis
  - path: patch-sealed-secrets.yaml
    target:
      kind: HelmRelease
      name: sealed-secrets
  - path: patch-traefik.yaml
    target:
      kind: HelmRelease
      name: traefik
  - path: patch-weave-gitops.yaml
    target:
      kind: HelmRelease
      name: weave-gitops