apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: patch-all-secrets-use-sealed-secrets.yaml
    target:
      kind: HelmRelease
  - path: patch-traefik-release.yaml
    target:
      kind: HelmRelease
      name: traefik
  - path: patch-mariadb-release.yaml
    target:
      kind: HelmRelease
      name: mariadb
  - path: patch-openldap-release.yaml
    target:
      kind: HelmRelease
      name: openldap
   - path: patch-redis-release.yaml
    target:
      kind: HelmRelease
      name: redis