apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: patch-traefik-values.yaml
    target:
      kind: HelmRelease
      name: traefik
  - path: patch-authelia-values.yaml
    target:
      kind: HelmRelease
      name: authelia
