apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
spec:
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              version: v1
              kind: Secret
            patch:
              - op: add
                path: "/metadata/annotations/sealedsecrets.bitnami.com~1managed"
                value: "true"