apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  chart:
    spec:
      version: 4.7.1
  values:
    controller:
      nodeSelector:
        ng: web
      admissionWebhooks:
        patch:
          nodeSelector:
            ng: web
      resources:
        limits:
          cpu: 300m
          memory: 300Mi
        requests:
          cpu: 300m
          memory: 300Mi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 30
        targetCPUUtilizationPercentage: 70
        targetMemoryUtilizationPercentage: 98