apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: foo
spec:
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            spec:
              template:
                spec:
                  nodeSelector:
                    ng: web

  