apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: required-for-kustomize-but-not-used
spec:
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            metadata:
              annotations:
                sealedsecrets.bitnami.com/managed: "true"