apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: mariadb
spec:
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            spec:
              template:
                spec:
                  nodeSelector:
                    ng: data
  
  # values:
  #   initdbScriptsConfigMap: mariadb-initdb-config.yaml
