apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: web
spec:
  releaseName: authelia
  chart:
    spec:
      chart: authelia
      version: '>=0.8.57,<1.0.0'
      sourceRef:
        kind: HelmRepository
        name: authelia
  interval: 50m
  # Default values
  # https://github.com/authelia/chartrepo/blob/master/charts/authelia/values.yaml
  # values:
    