apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  targetNamespace: redis
  releaseName: redis
  chart:
    spec:
      chart: redis
      version: '17.11.6'
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
  interval: 50m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    