apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
  labels:
    ng: data
spec:
  releaseName: sealed-secrets
  targetNamespace: sealed-secrets
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: sealed-secrets
      version: "1.4.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 50m