apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      version: '0.22.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 50m