---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: ${acmeEmail}
    server: ${acmeServer}
    privateKeySecretRef:
      name: letsencrypt-traefik
    solvers:
      - http01:
          ingress:
            class: traefik