apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tigera-operator
  namespace: flux-system
spec:
  releaseName: tigera-operator
  serviceAccountName: helm-controller
  targetNamespace: tigera-operator
  chart:
    spec:
      chart: tigera-operator
      version: v3.26.1
      sourceRef:
        kind: HelmRepository
        name: projectcalico
        namespace: flux-system
  # install:
  #   crds: CreateReplace
  # upgrade:
  #   crds: CreateReplace
  interval: 1m
  values:
    installation:
      kubernetesProvider: EKS