apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
  namespace: flux-system
spec:
  releaseName: openldap
  chart:
    spec:
      chart: openldap
      version: '4.1.1'
      sourceRef:
        kind: HelmRepository
        name: openldap
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 50m